<style>
textarea {
	font-size: 9px;
	line-height: 11px;
}

.table th,.table td {
	line-height: 10px;
}

input[type="radio"],input[type="checkbox"] {
	margin: -4px 0 0;
}
</style>

<div class="content-autorizaciones" id="catalogo-content" style="padding: 10px;">
	<div class="row-fluid">
		<div class="span12">
			<?php if( count($this->comentarios) > 0){ ?>
				<table class="table table-bordered">
				  	<thead style="font-size: 10px;" >
				    	<tr style="background-color:#343467;color:#fff;" >
							<th colspan="9" style="text-align:center;"><b>SEGUIMIENTO DE AUTORIZACIONES</b></th>
						</tr>
				    	<tr style="background-color:#999;color: #fff;">
				      		<th>Autorización</th>
				      		<th>Justificación</th>
				      		<th>Autorizador</th>
				      		<th>Resultado</th>
				      		<th>Fecha autorizada</th>
				      		<th>Comentarios</th>
				    	</tr>
				  	</thead>
				  	<tbody style="font-size: 8px;">
				    	<?php foreach($this->comentarios as $item): ?>
				    	<tr>
				      		<td><?php echo $item['TIPOAUTORIZA']; ?></td>
				      		<td><?php echo ($item['JUSTIFICACION']); ?></td>
				      		<td><?php echo $item['NOMBREAUTORIZA']; ?></td>
				      		<td><?php echo $item['RESULTADO']; ?></td>
				      		<td><?php echo $item['FECAUTORIZA']; ?></td>
				      		<td><?php echo $item['COMEAUTORIZA']; ?></td>
				    	</tr>
				    	<?php endforeach; ?>
				  	</tbody>
				</table>			
			<?php } ?>
		</div>
	</div>
	<div class="row-fluid">
		<div class="span12" id="lista-autorizaciones">
			<?php echo $this->html; ?>
<!--			<table class="table table-bordered">--> <!--				<thead>--> <!--					<tr style="background-color:#343467;color:#fff;" >-->
				<!--						<th colspan="9" style="text-align:left;"><b>ETAPAS/CÓDIGOS ::::</b></th>-->
				<!--					</tr>--> <!--			    	<tr style="background-color:#999;color: #fff;">-->
				<!--			      		<th style="text-align:center;">Categoria/Subcategoria/Concepto</th>-->
				<!--			      		<th style="text-align:center;">Crédito</th>--> <!--			      		<th style="text-align:center;">Ligas</th>-->
				<!--			      		<th>Det alarma</th>--> <!--			      		<th>Justificación</th>-->
				<!--			      		<th style="width: 160px;"><i class="icon-user"></i>Claudia Flores</th>-->
				<!--			      		<th style="width: 160px;"><i class="icon-user"></i>J Carlos Cabrera</th>-->
				<!--			      		<th style="width: 160px;"><i class="icon-user"></i>Miguel Martinez</th>-->
				<!--			    	</tr>--> <!--			  	</thead>--> <!--			  	<tbody style="font-size: 8px;">-->
				<!--			    	<tr>--> <!--			      		<td>CONCEPTODIGITALIZACIÓN DE EXPEDIENTES</td>-->
				<!--			      		<td>000000000000001<BR>JUAN JOSÉ LÓPEZ TORRES</td>-->
				<!--			      		<td><a href="#" >X1</a>&nbsp;&nbsp;&nbsp;&nbsp;<a href="#">X5</a></td>-->
				<!--			      		<td>Los detalles de alarma son</td>--> <!--			      		<td>Aqui va la Justificación</td>-->
				<!--			      		<td><input name="EtapCod_aut1" type="radio" checked="checked" />Si&nbsp;&nbsp;<input name="EtapCod_aut1" type="radio" />No</br>-->
				<!--			      		<textarea rows="" cols="" style="width: 100px;height: 27px;" maxlength="100"></textarea>-->
				<!--			      		</td>--> <!--			      		<td><input name="EtapCod_aut2" type="radio" checked="checked" />Si&nbsp;&nbsp;<input name="EtapCod_aut2" type="radio" />No</br>-->
				<!--			      		<textarea rows="" cols="" style="width: 100px;height: 27px;" maxlength="100"></textarea>-->
				<!--			      		</td>--> <!--			      		<td><input name="EtapCod_aut3" type="radio" checked="checked" />Si&nbsp;&nbsp;<input name="EtapCod_aut3" type="radio" />No</br>-->
				<!--			      		<textarea rows="" cols="" style="width: 100px;height: 27px;" maxlength="100"></textarea>-->
				<!--			      		</td>--> <!--			    	</tr>--> <!--			    	<tr>--> <!--			      		<td>CONCEPTODIGITALIZACIÓN DE EXPEDIENTES</td>-->
				<!--			      		<td>000000000000001<BR>JUAN JOSÉ LÓPEZ TORRES</td>-->
				<!--			      		<td><a href="#" >X1</a>&nbsp;&nbsp;&nbsp;&nbsp;<a href="#">X5</a></td>-->
				<!--			      		<td>Los detalles de alarma son</td>--> <!--			      		<td>Aqui va la Justificación</td>-->
				<!--			      		<td><input name="EtapCod_aut11" type="radio" checked="checked" />Si&nbsp;&nbsp;<input name="EtapCod_aut11" type="radio" />No</br>-->
				<!--			      		<textarea rows="" cols="" style="width: 100px;height: 27px;" maxlength="100"></textarea>-->
				<!--			      		</td>--> <!--			      		<td><input name="EtapCod_aut22" type="radio" checked="checked" />Si&nbsp;&nbsp;<input name="EtapCod_aut22" type="radio" />No</br>-->
				<!--			      		<textarea rows="" cols="" style="width: 100px;height: 27px;" maxlength="100"></textarea>-->
				<!--			      		</td>--> <!--			      		<td><input name="EtapCod_aut33" type="radio" checked="checked" />Si&nbsp;&nbsp;<input name="EtapCod_aut33" type="radio" />No</br>-->
				<!--			      		<textarea rows="" cols="" style="width: 100px;height: 27px;" maxlength="100"></textarea>-->
				<!--			      		</td>--> <!--			    	</tr>--> <!--			  	</tbody>--> <!--			</table>-->
				<!--			<table class="table table-bordered">--> <!--				<thead>--> <!--					<tr style="background-color:#343467;color:#fff;">-->
				<!--						<th colspan="9" style="text-align:left;"><b>PAGOS DOBLES ::::</b></th>-->
				<!--					</tr>--> <!--			    	<tr style="background-color:#999;color: #fff;">-->
				<!--			      		<th style="text-align:center;">Categoria/Subcategoria/Concepto</th>-->
				<!--			      		<th style="text-align:center;">Crédito</th>--> <!--			      		<th style="text-align:center;">Ligas</th>-->
				<!--			      		<th>Det alarma</th>--> <!--			      		<th>Justificación</th>-->
				<!--			      		<th style="width: 160px;"><i class="icon-user"></i>Claudia Flores</th>-->
				<!--			      		<th style="width: 160px;"><i class="icon-user"></i>J Carlos Cabrera</th>-->
				<!--			      		<th style="width: 160px;"><i class="icon-user"></i>Miguel Martinez</th>-->
				<!--			    	</tr>--> <!--			  	</thead>--> <!--			  	<tbody style="font-size: 8px;">-->
				<!--			    	<tr>--> <!--			      		<td>CONCEPTODIGITALIZACIÓN DE EXPEDIENTES</td>-->
				<!--			      		<td>000000000000001<BR>JUAN JOSÉ LÓPEZ TORRES</td>-->
				<!--			      		<td><a href="#" >X1</a>&nbsp;&nbsp;&nbsp;&nbsp;<a href="#">X5</a></td>-->
				<!--			      		<td>Los detalles de alarma son</td>--> <!--			      		<td>Aqui va la Justificación</td>-->
				<!--			      		<td><input name="PagDob_aut1" type="radio" checked="checked" />Si&nbsp;&nbsp;<input name="PagDob_aut1" type="radio" />No</br>-->
				<!--			      		<textarea rows="" cols="" style="width: 127px;height: 40px;" maxlength="100"></textarea>-->
				<!--			      		</td>--> <!--			      		<td><input name="PagDob_aut2" type="radio" checked="checked" />Si&nbsp;&nbsp;<input name="PagDob_aut2" type="radio" />No</br>-->
				<!--			      		<textarea rows="" cols="" style="width: 127px;height: 40px;" maxlength="100"></textarea>-->
				<!--			      		</td>--> <!--			      		<td><input name="PagDob_aut3" type="radio" checked="checked" />Si&nbsp;&nbsp;<input name="PagDob_aut3" type="radio" />No</br>-->
				<!--			      		<textarea rows="" cols="" style="width: 127px;height: 40px;" maxlength="100"></textarea>-->
				<!--			      		</td>--> <!--			    	</tr>--> <!--			  	</tbody>--> <!--			</table>-->
				<!--			<table class="table table-bordered">--> <!--				<thead>--> <!--					<tr style="background-color:#343467;color:#fff;">-->
				<!--						<th colspan="9" style="text-align:left;"><b>JEFE INMEDIATO ::::</b></th>-->
				<!--					</tr>--> <!--			    	<tr style="background-color:#999;color: #fff;">-->
				<!--			      		<th style="width: 213px;" colspan="5" style="text-align:center;"></th>-->
				<!--			      		<th colspan="3"><i class="icon-user"></i>Miguel Martinez</th>-->
				<!--			    	</tr>--> <!--			  	</thead>--> <!--			  	<tbody style="font-size: 8px;">-->
				<!--			    	<tr>--> <!--			      		<td colspan="5"></td>--> <!--			      		<td colspan="3"><input name="JefInm_aut3" type="radio" checked="checked" />Si&nbsp;&nbsp;<input name="JefInm_aut3" type="radio" />No</br>-->
				<!--			      		<textarea rows="" cols="" style="width: 127px;height: 40px;" maxlength="100"></textarea>-->
				<!--			      		</td>--> <!--			    	</tr>--> <!--			  	</tbody>--> <!--			</table>-->
				<!--			<table class="table table-bordered">--> <!--				<thead>--> <!--					<tr style="background-color:#343467;color:#fff;">-->
				<!--						<th colspan="9" style="text-align:left;"><b>EMPRESA ::::</b></th>-->
				<!--					</tr>--> <!--			    	<tr style="background-color:#999;color: #fff;">-->
				<!--			      		<th style="width: 173px;" colspan="4" style="text-align:center;">Empresa</th>-->
				<!--			      		<th style="width: 114px;">Justificación</th>--> <!--			      		<th colspan="3"><i class="icon-user"></i>Miguel Martinez</th>-->
				<!--			    	</tr>--> <!--			  	</thead>--> <!--			  	<tbody style="font-size: 8px;">-->
				<!--			    	<tr>--> <!--			      		<td colspan="4"></td>--> <!--			      		<td>Aqui va la Justificación</td>-->
				<!--			      		<td colspan="3"><input name="Empresa_aut3" type="radio" checked="checked" />Si&nbsp;&nbsp;<input name="Empresa_aut3" type="radio" />No</br>-->
				<!--			      		<textarea rows="" cols="" style="width: 127px;height: 40px;" maxlength="100"></textarea>-->
				<!--			      		</td>--> <!--			    	</tr>--> <!--			  	</tbody>--> <!--			</table>-->
				<!--			<table class="table table-bordered">--> <!--				<thead>--> <!--					<tr style="background-color:#343467;color:#fff;">-->
				<!--						<th colspan="9" style="text-align:left;"><b>URGENCIA ::::</b></th>-->
				<!--					</tr>--> <!--			    	<tr style="background-color:#999;color: #fff;">-->
				<!--			      		<th style="width: 173px;" colspan="4" style="text-align:center;">Urgencia</th>-->
				<!--			      		<th style="width: 114px;">Justificación</th>--> <!--			      		<th colspan="3"><i class="icon-user"></i>Miguel Martinez</th>-->
				<!--			    	</tr>--> <!--			  	</thead>--> <!--			  	<tbody style="font-size: 8px;">-->
				<!--			    	<tr>--> <!--			      		<td colspan="4"></td>--> <!--			      		<td>Aqui va la Justificación</td>-->
				<!--			      		<td colspan="3"><input name="Urg_aut3" type="radio" checked="checked" />Si&nbsp;&nbsp;<input name="Urg_aut3" type="radio" />No</br>-->
				<!--			      		<textarea rows="" cols="" style="width: 127px;height: 40px;" maxlength="100"></textarea>-->
				<!--			      		</td>--> <!--			    	</tr>--> <!--			  	</tbody>--> <!--			</table>-->
		</div>
	</div>
</div>
				<!--<script type="text/javascript" src="<?php echo $this->baseUrl; ?>/js/gastos/autorizacion-index.js"></script>-->