
<style>
<!--
input#fpagoini,input#fpagofin {
    background: #fff;
    cursor: pointer;
} 
-->
</style>

<!-- Modal Alta Masiva Créditos ----- 3 -->
<div id="modalAltaMasiva" class="modal hide fade" tabindex="-1" role="dialog" aria-labelledby="modalAltaMasivaLabel" aria-hidden="true" style="left: 45%; width: 700px;top: 2%;">
  <div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
    <h3 id="modalAltaMasivaLabel"><i class="icon-list-alt" ></i> Alta masiva de cuentas</h3>
  	<div class="loading-search" style="display:none;position: absolute;right: right: 130px;width: 200px;top: 21px;"><img alt="Cargando..." src="<?php echo $this->baseUrl; ?>/images/loading.gif" width="600px" height="390px" ></div>
  	<a class="btn btn-primary" id="btnConceptosValidos" style="position: absolute;top: 12px;left: 528px;" ><i class="icon-book icon-white" style="margin-top: 0px;"></i> Mis conceptos</a>
  </div>
  <div class="modal-body">
  	<form id="frmAltaMasiva" name="frmAltaMasiva" class="form-horizontal">
	  <div class="control-group" style="margin-bottom: 5px;" >
	    <h3 id="concepetoSeleccionadoLabel"></h3>
<!--	    <label class="control-label" for="conceptoAltMas">Concepto</label>-->
<!--	    <div class="controls">-->
<!--	      <select id="conceptoAltMas" name="conceptoAltMas" >-->
<!--	      	<option value="">-Seleccione-</option>-->
<!--	      </select>-->
<!--	    </div>-->
	  </div>
	  <div id="muestaConceptosValidos" class="alert alert-block alert-info fade in" style="position: absolute;left: 400px;top: 35px;padding: 8px 5px 8px 1px;color: #050505;background-color: #d0d0d0;border-color: #D0D0F4;display:none;" >
        <ul>
        	<?php foreach ($this->misconceptos as $item): ?>
        	<li><strong><?php echo $item['IDCONCEPTO']; ?> - </strong><?php echo $item['NMCONCEPTO']; ?></li>
        	<?php endforeach; ?>
        </ul>
	</div>
	  <div class="control-group" style="margin-bottom: 5px;">
	    <label class="control-label" for="file_upload" style="width: 115px;"><a href="<?php echo $this->baseUrl; ?>/images/CARGAMASIVA_LAYOUT.csv">Descargar layout</a></label>
	  </div>
	  <div class="control-group" style="margin-bottom: 5px;">
	    <label class="control-label" for="file_upload" style="width: 115px;">1) Carga archivo</label>
	  </div>
	  <div class="control-group" style="margin-bottom: 5px;padding-left: 167px;">
	  	    <input type="file" name="file_upload" id="file_upload" />
	  	    <input type="hidden" name="archivo" id="archivo" value="" />
	  	    <input type="hidden" name="verificado" id="verificado" value="N" />
	  	    <input type="hidden" name="procesado" id="procesado" value="N" />
	  </div>
	   <div id="msjErrorUploadError" class="alert alert-error" style="display:none;">
	    	<button type="button" class="close" data-dismiss="alert">&times;</button>
	   		Error al subir archivo
	  </div>
	  <div id="msjErrorUploadSuccess" class="alert alert-success" style="display:none;">
	    	<button type="button" class="close" data-dismiss="alert">&times;</button>
	   		El archivo archivo.csv se cargó correctamente!
	  </div>
	  <div class="control-group" style="margin-bottom: 5px;padding-left: 55px;">
	    <label><b style="">NOTA</b>: Instrucciones de la carga de archivo.</label>
	    <span class="help-block" >El archivo debe ser CSV delimitado por COMAS. Sólo debe tener concepto,cuenta,importe,justificacion.</span>
	    <span class="help-block">El nombre del archivo NO debe tener caracteres especiales, Ñ, ñ, epacios.</span>
		<span class="help-block">En la columna de justificación no debe de haber comas en los comentarios.</span>
	    <span class="help-block">El tamaño del nommbre del archivo NO debe revasar los 15 caracteres.</span>
	  </div>
	  <div class="control-group" style="margin-bottom: 5px;">
	    <label class="control-label" for="importe">2) Validación de archivo</label>
	    <div class="controls">
	      <button id="verificacionAltMas" name="verificacionAltMas" class="btn btn-primary" type="button" style="background-image: -webkit-linear-gradient(top,#343467,#343467);background-color: #343467;">Verificación</button>
	    </div>
	  </div>
	  <div id="msjErrorValidaError" class="alert alert-error" style="display:none;">
	    	<button type="button" class="close" data-dismiss="alert">&times;</button>
	   		Error al subir archivo
	  </div>
	  <div id="msjErrorValidaSuccess" class="alert alert-success" style="display:none;">
	    	<button type="button" class="close" data-dismiss="alert">&times;</button>
	   		Error al subir archivo
	  </div>
	  <div class="control-group" style="margin-bottom: 5px;padding-left: 35px;">
	    <label>NOTA: Resultado de la verificación.</label>
	    <span class="help-block">Error Sí la información es incorrecta en formato.</span>
	    <span class="help-block">Error Sí los valores de los conceptos son erroneos.</span>
	    <span class="help-block">Error Sí un Crédito es INVALIDO.</span>
	  </div>
	  <div class="control-group" style="margin-bottom: 5px;">
	    <label class="control-label" for="importe" style="width: 175px;">3) Procesando las cuentas</label>
	    <div class="controls">
	      <button id="procesamientoAltMas" name="procesamientoAltMas" class="btn btn-primary" type="button">Procesamiento</button>
	    </div>
	  </div>
	  <div id="msjErrorProcesaError" class="alert alert-error" style="display:none;">
	    	<button type="button" class="close" data-dismiss="alert">&times;</button>
	   		Error al subir archivo
	  </div>
	  <div id="msjErrorProcesaSuccess" class="alert alert-success" style="display:none;">
	    	<button type="button" class="close" data-dismiss="alert">&times;</button>
	   		Error al subir archivo
	  </div>
	  <div class="control-group" style="margin-bottom: 5px;padding-left: 75px;">
	    <span class="help-block">Estatus:</span>
	    <span class="help-block">Total registros:</span>
	    <span class="help-block">Correctos:</span>
	    <span class="help-block">Incorrectos:</span>
	  </div>
	</form>
  </div>
  <div class="modal-footer">
    <button class="btn" data-dismiss="modal" aria-hidden="true">Cancelar</button>
    <button id="btnFinalizarAltaMasiva" name="btnFinalizarAltaMasiva" class="btn btn-primary">Finalizar</button>
  </div>
</div>
<!-- End Modal Alta Masiva Créditos -->
<div class="content-asignacion center col-md-10 mx-auto" id="catalogo-content">
    <form class="form-horizontal" id="frmAsignacion" name="frmAsignacion">
        <!--BEGIN Informacion en hidden necesaria-->
            <input type="hidden" id="empleadoid" name="empleadoid" value="<?php echo $this->empleadoid; ?>">
            <input type="hidden" id="solicitudid" name="solicitudid" value="<?php echo $this->solicitudid; ?>">
            <input type="hidden" id="tiposolicitud" name="tiposolicitud" value="<?php echo $this->tiposolicitud; ?>">
            <input type="hidden" id="tipocaptura" name="tipocaptura" value="<?php echo $this->tipocaptura; ?>">
            <input type="hidden" id="puestoid" name="puestoid" value="<?php echo $this->puestoid; ?>">
            <input type="hidden" id="usuariopm" name="usuariopm" value="<?php echo $this->usuariopm; ?>">
            <input type="hidden" id="appuid" name="appuid" value="<?php echo $this->appuid; ?>">
            <input type="hidden" id="conceptoactual" name="conceptoactual" value="<?php echo $this->miconcepto; ?>">
            <input type="hidden" id="clavecyber" name="clavecyber" value="<?php echo $this->clavecyber; ?>">
            <input type="hidden" id="esPagoServicio" name="esPagoServicio" value="N">
        <!--END Informacion en hidden necesaria-->

        <section id="selects" class="card">
            <div class="card-body">
                <!-- .form-group -->
                <div class="form-group">
                    <label class="control-label" for="conceptoBuscarTypehead">Busca un concepto
                        <i tabindex="0" class="fa fa-info-circle text-blue" data-toggle="tooltip" data-container="body" data-placement="right" title="Si conoces el concepto podrás buscarlo"></i>
                    </label>
                        <input type="search" class="form-control typeahead" id="conceptoBuscarTypehead" placeholder="Ej: Agua" autocomplete="off" >
                        <input type="hidden" id="conceptoBuscarHidden" >
                </div>


                <!-- /.form-group -->
            </div>
            <div class="card-body border-top">
                <div class="row">
                    <div class="col-md-4">
                        <!-- .form-group -->
                        <div class="form-group">
                            <div class="form-label-group">
                                <select class="custom-select" id="categoria" required="" name="categoria" <?php echo ($this->tipocaptura == "3")?'disabled':'' ?> >
                                    <option value="0">-Seleccione-</option>
                                    <?php foreach ($this->categorias as $item): ?>
                                        <option value="<?php echo $item['IDVALOR']; ?>"><?php echo $item['NMVALOR']; ?></option>
                                    <?php endforeach; ?>
                                </select>
                                <label class="control-label control-label-selectGroup"  for="categoria">Categoría</label>
                            </div>
                        </div>
                        <!-- /.form-group -->
                    </div>
                    <div class="col-md-4">
                        <!-- .form-group -->
                        <div class="form-group">
                            <div class="form-label-group">
                                <select class="custom-select" required="" id="subcategoria" name="subcategoria" <?php echo ($this->tipocaptura == "3")?'disabled':'' ?> >
                                    <option value="0">-Seleccione-</option>
                                    <?php foreach ($this->conceptosByPuestoTC['arraySubCategoriaView'] as $item){
                                            foreach ($item as $i){
                                    ?>
                                        <option class="hide" data-categoria="<?php echo $i['IDCATEGORIA']; ?>" value="<?php echo $i['IDSUBCATEGORIA']; ?>"><?php echo $i['SUBCATEGORIA']; ?></option>
                                    <?php
                                            }
                                         }
                                    ?>
                                </select>
                                <label class="control-label control-label-selectGroup" for="subcategoria">Subcategoría</label>
                            </div>
                        </div>
                        <!-- /.form-group -->
                    </div>
                    <div class="col-md-4">
                        <!-- .form-group -->
                        <div class="form-group">
                            <div class="form-label-group">
                                <select class="custom-select" required="" id="conceptoid" name="conceptoid" <?php echo ($this->tipocaptura == "3")?'disabled':'' ?> >
                                    <option value="0">-Seleccione-</option>
                                    <?php foreach ($this->conceptosByPuestoTC['arrayConceptoView'] as $item){
                                        foreach ($item as $i){
                                            ?>
                                            <option class="hide" data-subcategoria="<?php echo $i['IDSUBCATEGORIA']; ?>" value="<?php echo $i['IDCONCEPTO']; ?>"><?php echo $i['CONCEPTO']; ?></option>
                                            <?php
                                        }
                                    }
                                    ?>
                                </select>
                                <label class="control-label control-label-selectGroup" for="conceptoid">Concepto</label>
                            </div>
                        </div>
                        <!-- /.form-group -->
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-4">
                        <div class="form-group">
                            <!-- .form-group -->
                            <div class="form-label-group">
                                <select class="custom-select form-control" required="" id="cartera" name="cartera"  <?php echo ($this->tipocaptura == "3")?'disabled':'' ?> >
                                    <option value="0">-Seleccione cartera-</option>
                                    <?php foreach ($this->carteras as $item): ?>
                                        <option value="<?php echo $item['IDVALOR']; ?>"><?php echo $item['NMVALOR']; ?></option>
                                    <?php endforeach; ?>
                                </select>

                                <label class="control-label control-label-selectGroup" for="cartera">Cartera</label>
                            </div>
                        <!-- /.form-group -->

                        </div>
                    </div>
                    <div class="col-md-4">
                        <div class="form-group">
                            <!-- .form-group -->
                            <div class="form-label-group">
                                <input class="form-control" id="gCentroCosto" type="email" placeholder="e.g. johndoe@looper.com" disabled="">
                                <label class="control-label" for="gCentroCosto">Grupo centro costo</label>
                            </div>
                            <!-- /.form-group -->
                        </div>
                    </div>
                    <div class="col-md-4">
                        <div class="form-group">
                        <!-- .form-group -->
                            <div class="form-label-group">
                                <input class="form-control" id="centroCosto" type="email" placeholder="e.g. johndoe@looper.com" value="BBVA" disabled="">
                                <label class="control-label" for="centroCosto">Centro Costo</label>
                            </div>
                        <!-- /.form-group -->
                        </div>
                    </div>
                </div>
            </div>
            <div class="card-body border-top">
                <div class="row">
                    <!-- .form-group -->
                    <div class="col-md-4">
                        <div class="form-group">
                            <div class="form-label-group">
                                <input type="text" class="form-control" id="cuenta" name="cuenta" placeholder="Cuentas" <?php echo ($this->tipocaptura == "3" || $this->tipocaptura == "4" || $this->tipocaptura == "42")?'disabled':'' ?>>
                                <label for="cuenta">Cuentas</label>
                            </div>
                        </div>
                        <!-- /.form-group -->
                    </div>
                    <div class="col-md-4">
                        <!-- .form-group -->
                        <div class="form-group">
                            <div class="form-label-group">
                                <input type="text" class="form-control" id="importe" name="importe" maxlength="12" placeholder="Importe sin IVA">
                                <label for="importe">Importe sin IVA</label>
                            </div>
                        </div>
                        <!-- /.form-group -->
                    </div>
                    <div class="col-md-4 planviaje hide">
                        <!-- .form-group -->
                        <div class="form-group">
                            <div class="form-label-group">
                                <input type="text" class="form-control cidplanviaje" id="planviaje" name="planviaje" placeholder="Plan de viaje">
                                <label for="importe">Plan de viaje</label>
                                <input id="idconceptopv" name="idconceptopv" type="hidden" >
                                <input id="perfilconcepto" name="perfilconcepto" type="hidden" >
                                <input type="hidden" id="isvalidPlan" name="isvalidPlan" value=0 >
                            </div>
                        </div>
                        <!-- /.form-group -->
                    </div>
                    <div class="col-md-4 fechaejecuta hide">
                        <!-- .form-group -->
                        <div class="form-group">
                            <div class="form-label-group">
                                <input type="text" class="form-control fechaejecucion" id="fechaejec" name="fechaejec" placeholder="Fecha ejecuci&oacute;n">
                                <label for="importe">Fecha ejecuci&oacute;n</label>
                                <input id="isFechaejec" name="isFechaejec" type="hidden" >
                            </div>
                        </div>
                        <!-- /.form-group -->
                    </div>

                </div>
            </div>
            <div class="card-body border-top pagoserv hide" >
                <div class="row">
                    <div class="col-md-4">
                        <div class="form-group">
                            <div class="form-label-group">
                                <input type="text" class="form-control fechapagoserv"  id="fpagoini" name="fpagoini" maxlength="12" placeholder="Fecha inicio" readonly>
                                <label for="fpagoini">Fecha inicio</label>
                            </div>
                        </div>
                    </div>
                    <div class="col-md-4">
                        <div class="form-group">
                            <div class="form-label-group">
                                <input type="text" class="form-control fechapagoserv" id="fpagofin" name="fpagofin" maxlength="12" placeholder="Fecha fin" readonly>
                                <label for="fpagofin">Fecha fin</label>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="card-body border-top" >
            <div class="row">
                <div class="col-md-10"></div>
                <div class="col-md-2">
                    <div class="form-actions">
                        <button class="btn btn-primary btn-lg btn-block" type="button" id="btnAgregarAsignacion" name="btnAgregarAsignacion" >Agregar</button>
                    </div>
                </div>
            </div>
        </div>
        </section>
    </form>

	<div class="row-fluid">
		<div class="span12" id="lista-asignaciones">
			
		</div>
	</div>

</div>
<script  type="text/javascript">
    var conceptosByPuestoTC = <?php echo $this->conceptosByPuestoTC['arrayConceptosBuscardor']  ?>;
    var arrayFilters = <?php echo $this->conceptosByPuestoTC['arrayFilters']  ?>;
    var arrayCategoria = <?php echo $this->conceptosByPuestoTC['arrayCategoria']  ?>;
    var arraySubCategoria = <?php echo $this->conceptosByPuestoTC['arraySubCategoria']  ?>;
    var arrayConcepto = <?php echo $this->conceptosByPuestoTC['arrayConcepto']  ?>;
</script>
<script type="text/javascript" src="<?php echo $this->baseUrl; ?>/js/gastos/asignacion-index.js?v=3.4.6"></script>