<!DOCTYPE html>
<html lang="es">
  <head>
    <title>Pendulum - Catalogos</title>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <!-- Bootstrap -->
    
    <link href="<?php echo $this->baseUrl; ?>/css/main.min.css" rel="stylesheet" media="screen">
    <link href="<?php echo $this->baseUrl; ?>/css/archivo.min.css" rel="stylesheet" media="screen">
    <link href="<?php echo $this->baseUrl; ?>/lib/bootstrap/css/bootstrap.min.css" rel="stylesheet" media="screen">

  </head>
  <body>
  	<div id="archivo" class="container">
  		<div class="row-fluid">
    		<div class="span12" id="catalogo-content">
    			<div class="hero-unit">
					<h1>Acceso no autorizado!</h1>
				    <p>No tiene permisos para acceder a éste módulo. Verifique con el administrador.</p>
				<!--    <p><a href="#" class="btn btn-primary btn-large">Learn more »</a></p>-->
				</div>
    		</div>
  	 	</div>
  	</div>
  	<script type="text/javascript" src="http://code.jquery.com/jquery.js"></script>
    <script type="text/javascript" src="<?php echo $this->baseUrl; ?>/lib/bootstrap/js/bootstrap.min.js"></script>
	 
  	<script type="text/javascript" src="<?php echo $this->baseUrl; ?>/js/catalogos/layout.js"></script>
  	<!-- End Scripts -->
  </body>
</html>
