<?php if( count($this->asignaciones) > 0 ) { ?>
<table class="table table-bordered">
	<thead>
    	<tr>
      		<th>Categoría/Subcategoría</th>
      		<th>Concepto</th>
      		<th><?php echo $this->tipocapturaLabel;?></th>
      		<th style="text-align:center;">Importe</th>
      		<th>Acciones</th>
    	</tr>
  	</thead>
  	<tbody>
  		<?php $total = 0;  foreach($this->asignaciones as $item): ?>
    	<tr>
      		<td><?php echo $item['CATEGSUB'];?></td>
      		<td><?php echo $item['NMCONCEPTO'];?></td>
      		<td><?php echo $item['CREDITO'];?>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<?php echo $item['CENTROCOSTOS'];?><br><?php echo utf8_encode($item['DEUDOR']);?></td>
      		<td style="text-align:right;padding-top: 14PX;" ><?php echo $item['IMPORTECOMAS'];?></td>
      		<td><?php if( $item["IDTIPOMOVTO"] == "2" || $item["IDTIPOMOVTO"] == "3"){ ?><a href="#" style="font: normal 11px arial, tahoma, helvetica, sans-serif;" class="linkX1" rel="<?php echo $item['CREDITO'];?>">X1</a>&nbsp;&nbsp;&nbsp;<a href="#" style="font: normal 11px arial, tahoma, helvetica, sans-serif;" class="linkX5" rel="<?php echo $item['CREDITO'];?>">X5</a>&nbsp;&nbsp;&nbsp;<?php }?><a href="#" class="removeAsigna" rel="<?php echo $item['VALOR'];?>" credito="<?php echo $item['CREDITO'];?>" concepto="<?php echo $item['IDCONCEPTO'];?>" nmconcepto="<?php echo $item['NMCONCEPTO'];?>"><i class="icon-remove" ></a></td>
    	</tr>
    	<?php $total += (float)$item['IMPORTE']; endforeach; ?>
  	</tbody>
  	<tfoot>
  		<tr>
  			<th colspan="3" style="text-align:right;">Total</th>
      		<th style="text-align:right;"><?php echo "$ " .  number_format($total, 2, ".", ","); ?></th>
      		<th></th>
    	</tr>
  	</tfoot>
</table>
<?php } else { ?>
	<p>No hay registros</p>
<?php } ?>
<script type="text/javascript"> 
	AsignacionExterno.fnTableAsignacion();
</script>