<div class="content-comprobacion" id="catalogo-content">
	<div class="row-fluid">
		<div class="span6">
			<label for="tipoAsignacion">
				<input type="hidden" id="solicitudid" name="solicitudid" value="<?php echo $this->solicitudid; ?>" >
				<input type="hidden" id="empleadoid" name="empleadoid" value="<?php echo $this->empleadoid; ?>" >
			</label>
		</div>
		<div class="span6" style="padding-left: 480px;">
			
		</div>
	</div>
	<div class="row-fluid">
		<div class="span12" id="lista-montosolicitud">
			<table class="table table-bordered">
				<thead>
			    	<tr>
			      		<th>Categoría/Subcategoría</th>
			      		<th>Concepto</th>
			      		<th>Cuenta/Cartera/Concepto</th>
			      		<th style="text-align:center;">Importe solicitado</th>
			      		<th style="text-align:center;">Importe real</th>
			      		<th>Acciones</th>
			    	</tr>
			  	</thead>
			  	<tbody>
<!--			    	<tr>-->
<!--			      		<td>Cat->GASTOS ADMINISTRACIÓN<BR>Subcat->ALMACENAMIENTO Y DIGITALIZACIÓN</td>-->
<!--			      		<td>CONCEPTODIGITALIZACIÓN DE EXPEDIENTES</td>-->
<!--			      		<td>000000000000001<BR>JUAN JOSÉ LÓPEZ TORRES</td>-->
<!--			      		<td style="text-align:right;" >$85,254.00</td>-->
<!--			      		<td style="text-align:right;" >$85,254.00</td>-->
<!--			      		<td><a href="#" >X1</a><a href="#">X5</a><i class="icon-remove " style="margin-top: 9px;"></td>-->
<!--			    	</tr>-->
			  	</tbody>
			</table>
		</div>
	</div>
	<div class="row-fluid">
		<div class="span6">
		</div>
		<div class="span6" style="padding-left: 480px;text-align: right;">
<!--			<button class="btn btn-success" id="bntGuardarComprobacion" name="bntGuardarComprobacion">Guardar</button>-->
		</div>
	</div>
</div>